### ISSUE TITLE
这个可以接本地大模型服务么？比如ollama部署的。

### ISSUE THREAD

**Issue by oldonecode** [GAIR-NLP/PC-Agent#2]
这个可以接本地大模型服务么？比如ollama部署的。

**Comment by HenryHe0123** [comment]
Yes, you can integrate with local LLM services like Ollama.
We support OpenAI API-compatible services - you can find details in our implementation at https://github.com/GAIR-NLP/PC-Agent/blob/main/agent/main.py#L6.
