### ISSUE TITLE
Copy-Item : can't find the file: “D:\code\github\PC-Agent\tracker\__files__”， the file __files__  is not exist。

### ISSUE THREAD

**Issue by disunlike** [GAIR-NLP/PC-Agent#3]
PS D:\code\github\PC-Agent\tracker> .\package.ps1
dist folder cleared.
411 INFO: PyInstaller: 6.11.1, contrib hooks: 2024.11
412 INFO: Python: 3.12.0 (conda)
438 INFO: Platform: Windows-10-10.0.19044-SP0
438 INFO: Python environment: C:\Users\y\.conda\envs\chat-db-service
444 INFO: Module search paths (PYTHONPATH):
['C:\\Users\\y\\.conda\\envs\\chat-db-service\\Scripts\\pyinstaller.exe',
 'C:\\Users\\y\\.conda\\envs\\chat-db-service\\python312.zip',
 'C:\\Users\\y\\.conda\\envs\\chat-db-service\\DLLs',
 'C:\\Users\\y\\.conda\\envs\\chat-db-service\\Lib',
 'C:\\Users\\y\\.conda\\envs\\chat-db-service',
 'C:\\Users\\y\\AppData\\Roaming\\Python\\Python312\\site-packages',
 'C:\\Users\\y\\AppData\\Roaming\\Python\\Python312\\site-packages\\win32',
 'C:\\Users\\y\\AppData\\Roaming\\Python\\Python312\\site-packages\\win32\\lib',
 'C:\\Users\\y\\AppData\\Roaming\\Python\\Python312\\site-packages\\Pythonwin',
 'C:\\Users\\y\\.conda\\envs\\chat-db-service\\Lib\\site-packages',
 'C:\\Users\\y\\AppData\\Roaming\\Python\\Python312\\site-packages\\setuptools\\_vendor',
 'D:\\code\\github\\PC-Agent\\tracker']
1203 INFO: checking Analysis
1281 INFO: checking PYZ
1336 INFO: checking PKG
1372 INFO: Bootloader C:\Users\y\.conda\envs\chat-db-service\Lib\site-packages\PyInstaller\bootloader\Windows-64bit-intel\runw.exe
1372 INFO: checking EXE
1388 INFO: Rebuilding EXE-00.toc because tracker.exe missing
1389 INFO: Building EXE from EXE-00.toc
1390 INFO: Copying bootloader EXE to D:\code\github\PC-Agent\tracker\dist\tracker.exe
1395 INFO: Copying icon to EXE
1398 INFO: Copying 0 resources to EXE
1398 INFO: Embedding manifest in EXE
1401 INFO: Appending PKG archive to EXE
1419 INFO: Fixing EXE headers
1818 INFO: Building EXE from EXE-00.toc completed successfully.
tracker.exe successfully created.
Copy-Item : 找不到路径“D:\code\github\PC-Agent\tracker\__files__”，因为该路径不存在。
所在位置 D:\code\github\PC-Agent\tracker\package.ps1:28 字符: 1
+ Copy-Item -Path "./__files__" -Destination "./dist/" -Recurse -Force
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (D:\code\github\...acker\__files__:String) [Copy-Item], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.CopyItemCommand

tasks.json is now hidden.
task_cnt.json is now hidden.
Error: __files__ not found in ./dist/.

**Comment by HenryHe0123** [comment]
Hi, thank you for your interest in our project!
We've recently updated the PC Tracker codebase. You can either download PC Tracker v1.0 release or clone and build from source with the updated structure.
