### ISSUE TITLE
Request for training scripts and parameters of your trained model

### ISSUE THREAD

**Issue by xwong22** [GAIR-NLP/PC-Agent#4]
Hi, thanks for the great work! 

May I know when will you be releasing the training scripts and parameters of your trained model? 
Interested in the project, would like to train with some of my collected trajectories and play around with your trained model. 

Looking forward to your reply!

**Comment by zizi0123** [comment]
Thank you for your interest in our work and willingness to experiment with it! We recommend organizing training data as described in our paper and conducting training using llama-factory. We are conducting further training and more extensive experiments, and will open-source the models afterwards.

**Comment by xwong22** [comment]
Thanks for the recommendation. Looking forward to your open-source models!
