### ISSUE TITLE
some problem I find in my PC

### ISSUE THREAD

**Issue by disunlike** [GAIR-NLP/PC-Agent#5]
The problems I detected are: 
1. Poor compatibility. When simulating the mouse and keyboard operation of the computer, the click frequently fails to locate the exact position. The reason is presumed to be that the author's screen resolution and software version are different from mine, and he may have tuned the code logic for his own environment (I didn't look at the code closely, only speculate). 
3. Very token expensive, about 10 interactions for 3 cents. It is possible to replace the model with open source, but the effect will be worse. 
4. The interaction speed is very slow, and it may not be appropriate to study GUI+AI by using PPT production as the scene. PPT production can currently be used as a token generation task without interaction.
--
I think we should change the scene. Let the agent do the PPT generation is equivalent to let the humanoid robot drive the fuel car to realize the automatic driving, which becomes more difficult.

**Comment by zizi0123** [comment]
Thank you for your feedback! Here's our response:

1. As mentioned in our paper, visual grounding capability is essential for effective click execution, and we use Molmo with self-validation mechanism to implement this. We are working to ensure broader compatibility.
2. Our entire agent system is based on open-source models. We trained the planning model to enhance its performance.
3. We believe that human-like GUI interaction methods have broader generality and can provide agents with greater potential. PPT production is merely our preliminary experimental validation scenario, as it presents sufficient complexity to demonstrate the capabilities of agents.
